name: build-site-data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "10 6 * * *"   # daily 06:10 UTC
  push:
    branches: [ main ]
    paths:
      - "reports/**"
      - "scripts/**"
      - "!docs/**"         # don't retrigger on our own data commit

permissions:
  contents: write

concurrency:
  group: build-site-data-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Build site data (posts.json + reports.json + audio.json)
        run: python scripts/build_site_data.py

      # ---- rebase-safe commit using a PAT that can update workflows ----
      - name: Commit & push data (via PAT)
        env:
          PAT_WORKFLOW: ${{ secrets.PAT_WORKFLOW }}
          REPO: ${{ github.repository }}
        run: |
          set -e

          git config user.name  "automation"
          git config user.email "actions@users.noreply.github.com"

          # Stage only the generated data files
          git add docs/data/posts.json docs/data/reports.json docs/data/audio.json || true

          # Nothing to do?
          if git diff --cached --quiet; then
            echo "No data changes to commit."
            exit 0
          fi

          # Make sure we’re on top of the latest main (rebase-safe)
          git fetch origin main
          git pull --rebase origin main

          git commit -m "Build site data $(date -u +%F)"

          # Push using PAT (allows workflow file to exist in history)
          git remote set-url origin https://${PAT_WORKFLOW}@github.com/${REPO}.git
          git push origin HEAD:main
