- name: Commit & push data (via PAT)
  env:
    PAT_WORKFLOW: ${{ secrets.PAT_WORKFLOW }}
    REPO: ${{ github.repository }}
  run: |
    set -e
    git config user.name  "automation"
    git config user.email "actions@users.noreply.github.com"

    # Stage only generated files
    git add docs/data/posts.json docs/data/reports.json docs/data/audio.json || true

    # Nothing to commit?
    if git diff --cached --quiet; then
      echo "No data changes to commit."
      exit 0
    fi

    # Rebase-safe: stay on top of the latest main
    git fetch origin main
    git pull --rebase origin main

    git commit -m "Build site data $(date -u +%F)"

    # Push using PAT
    git remote set-url origin https://${PAT_WORKFLOW}@github.com/${REPO}.git
    git push origin HEAD:main
