name: build-site-data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "10 6 * * *"   # daily 06:10 UTC
  push:
    branches: [ main ]
    paths:
      - "reports/**"
      - "scripts/**"
      # Explicitly ignore docs/ changes so our own commit doesn't retrigger
      - "!docs/**"

permissions:
  contents: write

# Run at most one per branch, but DO NOT cancel in-progress runs.
concurrency:
  group: build-site-data-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Build site data (posts.json + reports.json + audio.json)
        run: python scripts/build_site_data.py

      - name: Commit data (rebase-safe)
        run: |
          set -e
          git config user.name "automation"
          git config user.email "actions@users.noreply.github.com"

          git add docs/data/posts.json docs/data/reports.json docs/data/audio.json || true
          if git diff --cached --quiet; then
            echo "No data changes to commit."
            exit 0
          fi

          git fetch origin main
          git reset --soft origin/main
          git add docs/data/posts.json docs/data/reports.json docs/data/audio.json
          git commit -m "Build site data $(date -u +%F)"
          git push origin HEAD:main
