name: EUR-Lex Daily Digest

on:
  schedule:
    # 04:00 UTC ≈ 06:00 Amsterdam in summer (CEST), 05:00 in winter (CET)
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_FROM: ${{ secrets.MAILGUN_FROM }}
          MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
          # Optional: override default model
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          GOOGLE_SERVICE_ACCOUNT_JSON
          GOOGLE_DOCS_FOLDER_ID       (optional)
          GOOGLE_DOCS_SHARE_WITH      (optional)
        run: python main.py

      - name: Commit daily report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain reports)" ]; then
            git add reports
            git commit -m "Add daily report $(date -u +%F)"
            git push
          else
            echo "No changes in reports/"
          fi
