name: EUR-Lex Daily Digest

on:
  schedule:
    # 05:00 UTC ≈ 07:00 Amsterdam in summer (CEST), 06:00 in winter (CET)
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_FROM: ${{ secrets.MAILGUN_FROM }}
          MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
        run: python main.py
