name: Pipeline v2 (daily)

on:
  schedule:
    # GitHub Actions draait cron in UTC. 06:00 UTC = 08:00 Europe/Amsterdam (CEST).
    - cron: "0 6 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: daily-v2
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (best-effort)
        run: |
          python -V
          pip install -r requirements.txt || true
          pip install python-dateutil beautifulsoup4 lxml pyyaml orjson || true

      # 1) Discover laatste 24 uur (alle bronnen uit sources_v2.yaml)
      - name: Daily discover (last 24h)
        run: |
          python workers/weekly_discover.py --window 1d --sources sources_v2.yaml --config config_v2.yaml

      # 2) Verwerk documenten (samenvattingen e.d.)
      - name: Process documents
        run: |
          python workers/process_document.py --from state/latest_discovery.json --config config_v2.yaml --limit 50

      # 3) Bouw rolling timeline (7 dagen is prettig voor website)
      - name: Build timeline (rolling 7d)
        run: |
          python workers/build_timeline.py --window 7d --config config_v2.yaml

      # 4) Daily digest (MD + JSON → voor nieuwsbrief/website)
      - name: Build daily digest
        run: |
          python workers/build_daily_digest.py --hours 24

      # 5) Build site payload
      - name: Build site payload
        run: |
          if [ -f build_site_data.py ]; then
            # Gebruik jouw bestaande script indien aanwezig
            python build_site_data.py || true
          else
            # Fallback: minimale site data
            python workers/build_site_data_v2.py
          fi

      # Inspectie in logs
      - name: Show outputs (ls + head)
        run: |
          echo "== outputs/docs ==" && ls -lah outputs/docs || true
          echo "== outputs/timelines ==" && ls -lah outputs/timelines || true
          echo "== reports/daily ==" && ls -lah reports/daily || true
          echo "== docs/digests ==" && ls -lah docs/digests || true
          echo "== docs/data ==" && ls -lah docs/data || true
          for f in outputs/docs/*.ndjson; do echo "---- $f"; head -n 2 "$f" || true; done
          for f in outputs/timelines/*.json; do echo "---- $f"; head -n 40 "$f" || true; done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-v2-data
          path: |
            outputs/docs/*.ndjson
            outputs/timelines/*.json
            reports/daily/*.md
            docs/digests/*.json
            docs/data/*.json
          if-no-files-found: warn

      - name: Commit results back to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add outputs/docs outputs/timelines reports/daily docs/digests docs/data || true
          git commit -m "daily pipeline v2 $(date -u +'%F %T') [auto]" || echo "No changes to commit"
          git push
